### ISSUE TITLE
invalid syntax following upgrade to 1.3.7

### ISSUE THREAD

**Issue by chicago6061** [sfanous/Pyecobee#12]
ERROR:pyecobee.utilities:Missing attribute in class Event
Attribute name  => fanSpeed
Attribute value => low

Please open a new issue here (https://github.com/sfanous/Pyecobee/issues/new)
ERROR:pyecobee.utilities:Missing attribute in class Event
Attribute name  => fanSpeed
Attribute value => optimized

Please open a new issue here (https://github.com/sfanous/Pyecobee/issues/new)
ERROR:pyecobee.utilities:Missing attribute in class Event
Attribute name  => fanSpeed
Attribute value => low

Please open a new issue here (https://github.com/sfanous/Pyecobee/issues/new)
Traceback (most recent call last):
  File "./ecobee.py", line 274, in <module>
    thermostat_response = ecobee_service.request_thermostats(selection)
  File "/usr/local/lib/python3.5/dist-packages/pyecobee/service.py", line 292, in request_thermostats
    return Utilities.process_http_response(response, EcobeeThermostatResponse)
  File "/usr/local/lib/python3.5/dist-packages/pyecobee/utilities.py", line 325, in process_http_response
    is_top_level=True)
  File "/usr/local/lib/python3.5/dist-packages/pyecobee/utilities.py", line 243, in dictionary_to_object
    return eval(''.join(response_properties[parent_classes[0]]))
  File "<string>", line 646
    ,
    ^
SyntaxError: invalid syntax

**Comment by sherif-fanous** [comment]
v1.3.8 pushed to Github and published to PyPI.
